
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="icon" type="image/png" href="{{ asset('uploads/img/irms.png') }}">
    <title>Quarantine Report</title>
    <style>
        @page {
            margin: 20px 30px;
        }
        body {
            font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
        }
        
        .table-container {
            max-height: 700px;    
            overflow-y: auto;    
            border: 1px solid #ccc; 
            width: 100%;
        }
        table {
            width: 100%;
            border-collapse: collapse; 
            page-break-inside: auto; 
            
        }
        tr {
            page-break-inside: avoid;
            page-break-after: auto;
        }
        thead {
            display: table-header-group;
        }
        th {
            background-color: #4A5568;
            color: #ffffff;
            font-weight: bold;
            text-align: left;
            padding: 6px;
            font-size: 12px;
            text-transform: uppercase;
        }
        .td-data {
            padding: 4px 2px 2px 2px;
            border-bottom: 1px solid #E2E8F0;
            vertical-align: top;
            border-style: 1px solid;
            border-color: #a6aebd;
            font-size: 11.5px;
            line-height: 1.2;
        }
        h1{
            text-align:center; 
            font-size:20px; 
            font-weight:bold; 
            margin-top:25px; 
            letter-spacing:1px;
            
        }
        /* Zebra Striping */
        .tr-data:nth-child(even) {
            background-color: #F7FAFC;
        }

        .custom-button {
        display: inline-block;
        text-decoration: none;
        padding: 8px 15px;
        margin-bottom: 15px;
        background-color: #4A5568;
        color: #ffffff;
        font-family: sans-serif;
        font-size: 13px;
        font-weight: bold;
        text-align: center;
        border-radius: 10px;
        cursor: pointer;
        transition: background-color 0.2s ease-in-out;
        }

        .custom-button:hover {
        background-color: #6e7788;
        }

        .p-left
        {
            font-size: 10pt;
            margin-top: 10px;
            margin-left:10px;
            
        }
        .p-right
        {
            font-size: 10pt;
            margin-top: 10px;
            padding-right:10px;
        }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .font-semibold { font-weight: 600; }
    </style>
</head>
<body>

<table class ="header" width="100%" style="margin-bottom: 5px;">
    <tr>
        <td colspan="1" style="border-bottom:1px solid #4A5568;">
            <!--@if(isset($showDownload))
            <a href="javascript:history.back()" class="custom-button"> Back </a>
            @endif-->
        </td>
        <td colspan="1" align="center" style="border-bottom:1px solid #4A5568;">
            <h1>QUARANTINE REPORT</h1>
        </td>
        <td style="border-bottom:1px solid #4A5568;"></td>
    </tr>    
    
    <tr style="background-color:none;">
        <td class="td-header" width="33%" valign="top">
            <p class="p-left"><strong>Site:</strong> {{ $rssite }}</p>
            <p class="p-left"><strong>Total Quarantined Locations:</strong> {{ count($records) }}</p>
        </td>
        <td class="td-header" width="34%"></td>
        <td class="td-header" width="33%" valign="top" align="right">
            <p class="p-right"><strong>Date Generated:</strong> {{ date('F d, Y') }}</p>
            <p class="p-right" style="margin:px 0;"><strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}</p>
        </td>
    </tr>
</table>

    @if(!empty($showDownload))
        <a class="custom-button" href="{{ route('irms.quarantine-report.pdf', request()->all()) }}">
            Download Quarantine Report</a>
    @endif

    
@php
    $chunks = array_chunk($records ?? [], 25);
@endphp

@foreach($chunk as $record)
<div>
    <table>
        <thead>
            <tr>
                <th>WAREHOUSE</th>
                <th>BAY NO.</th>
                <th>LOCATION</th>
                <th>PALLET</th>
                <th>CO</th>
                <th>ITEM</th>
                <th>ITEM DESCRIPTION</th>
                <th>U/M</th>
                <th>QTY</th>
                <th>DATE RCVD.</th>
            </tr>
        </thead>
        <tbody>
            @forelse($chunk as $record)
                    <tr class="tr-data">
                        <td class="td-data">{{ $record->rswhse }}</td>
                        <td class="td-data">{{ $record->rsbaynum }}</td>
                        <td class="td-data">{{ $record->rsloc }}</td>
                        <td class="td-data">{{ $record->rspallet_num }}</td>
                        <td class="td-data">{{ $record->job }}</td>
                        <td class="td-data">{{ $record->item }}</td>
                        <td class="td-data">{{ $record->desc ?? '' }}</td>
                        <td class="td-data">{{ $record->um }}</td>
                        <td class="td-data">{{ number_format($record->qty ?? 0, 0) }}</td>
                        <td class="td-data">
                            {{ $record->datercvd ? \Carbon\Carbon::parse($record->datercvd)->format('d F Y') : '' }}
                        </td>

                    </tr>
            @empty
                <tr>
                    <td colspan="3">No data found</td>
                </tr>
            @endforelse
        </tbody>
        </table>
    </div>
    <div style="page-break-after: always;"></div>
    @endforeach
</body>
</html>
    
